#!/bin/bash
#BSUB -J "PostQC1_3aiXii[19]" 
#BSUB -P acc_funEpi
#BSUB -q premium
#BSUB -n 1
#BSUB -R affinity[core(2)]
#BSUB -R span[hosts=1]
#BSUB -R rusage[mem=16GB]
#BSUB -W 12:00
#BSUB -oo /sc/arion/projects/funEpi/Hara/SPARK_final/SPARK_final_postQC1/postQC1_output/PostQC1_3aiXii.stdout
#BSUB -eo /sc/arion/projects/funEpi/Hara/SPARK_final/SPARK_final_postQC1/postQC1_output/PostQC1_3aiXii.stderr

module load plink2/v2.00a3.3
chr=${LSB_JOBINDEX}
dir="/sc/arion/projects/funEpi/SPARK_Final1"
vcf="${dir}/chr${chr}.dose.vcf.gz"
impdir="/sc/arion/projects/funEpi/SPARK_Final1"
pgen="${impdir}/chr${chr}_HDS"


plink2 --pgen ${pgen}.pgen \
--psam ${pgen}.psam \
--pvar ${pgen}.pvar \
--minimac3-r2-filter 0.5 \
--maf 0.01 minor \
--make-bed \
--out ${impdir}/chr${chr}_clean  







