#!/bin/bash
#BSUB -J "PostQC_afr[1-22]" 
#BSUB -P acc_funEpi
#BSUB -q premium
#BSUB -n 1
#BSUB -R affinity[core(2)]
#BSUB -R span[hosts=1]
#BSUB -R rusage[mem=16GB]
#BSUB -W 12:00
#BSUB -oo /sc/arion/projects/funEpi/Hara/SPARK_all/SPARK_all_imputed/output/PostQC_afr.stdout
#BSUB -eo /sc/arion/projects/funEpi/Hara/SPARK_all/SPARK_all_imputed/output/PostQC_afr.stderr

module load plink/1.90b6.21

impdir="/sc/arion/projects/funEpi/Hara/SPARK_final/SPARK_merged"
chr=${LSB_JOBINDEX}





plink --bfile ${impdir}/chr${chr}_newrs --allow-no-sex --keep ${impdir}/cc_WESafr.txt --make-pheno ${impdir}/case_WESafr.txt '*' --make-bed --out ${impdir}/chr${chr}_finaleth
plink --bfile ${impdir}/chr${chr}_finaleth --allow-no-sex --logistic --ci 0.95 --geno 0.01 --maf 0.01 --hwe 1e-6 --covar ${impdir}/covarWESafr.txt --covar-number  3-12 --out ${impdir}/chr${chr}_adjrs_afr
grep "ADD" ${impdir}/chr${chr}_adjrs_afr.assoc.logistic > ${impdir}/chr${chr}finalrs_afr






