#!/bin/bash
#BSUB -J "Pre_QC5_all"
#BSUB -P acc_funEpi
#BSUB -q premium
#BSUB -n 2
#BSUB -R span[hosts=1]
#BSUB -R rusage[mem=16000]
#BSUB -W 24:00
#BSUB -oo /sc/arion/projects/funEpi/Hara/SPARK_all/output/Pre_QC5.stdout
#BSUB -eo /sc/arion/projects/funEpi/Hara/SPARK_all/output/Pre_QC5.stderr



module load plink/1.90b6.21 

plink --bfile /sc/arion/projects/funEpi/Hara/SPARK_all/results/WES1QC6 --keep /sc/arion/projects/funEpi/Hara/Pre_QC_SPARK/WES1/premature_cc.txt --make-bed --out /sc/arion/projects/funEpi/Hara/SPARK_all/results/WES1QC7
plink --bfile /sc/arion/projects/funEpi/Hara/SPARK_all/results/WES1QC7 --indep-pairwise 50 5 0.2 --out /sc/arion/projects/funEpi/Hara/SPARK_all/results/WES1_QC7prune
plink --bfile /sc/arion/projects/funEpi/Hara/SPARK_all/results/WES1QC7 --extract /sc/arion/projects/funEpi/Hara/SPARK_all/results/WES1_QC7prune.prune.in --het --out /sc/arion/projects/funEpi/Hara/SPARK_all/results/WES1_QC8a



